namespace CsharpGalexy.LibraryExtention.CountryDialCode
{
    public static class CountryDialCodeHelper
    {
        public class CountryDialCode
        {
            public string DialCode { get; set; }
            public string PersianCountryName { get; set; }
            public string EnglishCountryName { get; set; }
        }

        private static readonly List<CountryDialCode> CountryDialCodes = new List<CountryDialCode>
        {
            new CountryDialCode { DialCode = "+1", PersianCountryName = "آمریکا", EnglishCountryName = "United States" },
            new CountryDialCode { DialCode = "+1", PersianCountryName = "کانادا", EnglishCountryName = "Canada" },
            new CountryDialCode { DialCode = "+20", PersianCountryName = "مصر", EnglishCountryName = "Egypt" },
            new CountryDialCode { DialCode = "+25", PersianCountryName = "اوگاندا", EnglishCountryName = "Uganda" },
            new CountryDialCode { DialCode = "+27", PersianCountryName = "آفریقای جنوبی", EnglishCountryName = "South Africa" },
            new CountryDialCode { DialCode = "+30", PersianCountryName = "یونان", EnglishCountryName = "Greece" },
            new CountryDialCode { DialCode = "+31", PersianCountryName = "هلند", EnglishCountryName = "Netherlands" },
            new CountryDialCode { DialCode = "+32", PersianCountryName = "بلژیک", EnglishCountryName = "Belgium" },
            new CountryDialCode { DialCode = "+33", PersianCountryName = "فرانسه", EnglishCountryName = "France" },
            new CountryDialCode { DialCode = "+34", PersianCountryName = "اسپانیا", EnglishCountryName = "Spain" },
            new CountryDialCode { DialCode = "+36", PersianCountryName = "مجارستان", EnglishCountryName = "Hungary" },
            new CountryDialCode { DialCode = "+39", PersianCountryName = "ایتالیا", EnglishCountryName = "Italy" },
            new CountryDialCode { DialCode = "+39", PersianCountryName = "واتیکان", EnglishCountryName = "Vatican" },
            new CountryDialCode { DialCode = "+41", PersianCountryName = "سوئیس", EnglishCountryName = "Switzerland" },
            new CountryDialCode { DialCode = "+42", PersianCountryName = "چک", EnglishCountryName = "Czech Republic" },
            new CountryDialCode { DialCode = "+43", PersianCountryName = "اتریش", EnglishCountryName = "Austria" },
            new CountryDialCode { DialCode = "+44", PersianCountryName = "انگلستان", EnglishCountryName = "United Kingdom" },
            new CountryDialCode { DialCode = "+45", PersianCountryName = "دانمارک", EnglishCountryName = "Denmark" },
            new CountryDialCode { DialCode = "+46", PersianCountryName = "سوئد", EnglishCountryName = "Sweden" },
            new CountryDialCode { DialCode = "+47", PersianCountryName = "نروژ", EnglishCountryName = "Norway" },
            new CountryDialCode { DialCode = "+48", PersianCountryName = "لهستان", EnglishCountryName = "Poland" },
            new CountryDialCode { DialCode = "+49", PersianCountryName = "آلمان", EnglishCountryName = "Germany" },
            new CountryDialCode { DialCode = "+51", PersianCountryName = "پرو", EnglishCountryName = "Peru" },
            new CountryDialCode { DialCode = "+52", PersianCountryName = "مکزیک", EnglishCountryName = "Mexico" },
            new CountryDialCode { DialCode = "+53", PersianCountryName = "کوبا", EnglishCountryName = "Cuba" },
            new CountryDialCode { DialCode = "+54", PersianCountryName = "آرژانتین", EnglishCountryName = "Argentina" },
            new CountryDialCode { DialCode = "+55", PersianCountryName = "برزیل", EnglishCountryName = "Brazil" },
            new CountryDialCode { DialCode = "+56", PersianCountryName = "شیلی", EnglishCountryName = "Chile" },
            new CountryDialCode { DialCode = "+57", PersianCountryName = "کلمبیا", EnglishCountryName = "Colombia" },
            new CountryDialCode { DialCode = "+58", PersianCountryName = "ونزوئلا", EnglishCountryName = "Venezuela" },
            new CountryDialCode { DialCode = "+60", PersianCountryName = "مالزی", EnglishCountryName = "Malaysia" },
            new CountryDialCode { DialCode = "+61", PersianCountryName = "استرالیا", EnglishCountryName = "Australia" },
            new CountryDialCode { DialCode = "+62", PersianCountryName = "اندونزی", EnglishCountryName = "Indonesia" },
            new CountryDialCode { DialCode = "+63", PersianCountryName = "فیلیپین", EnglishCountryName = "Philippines" },
            new CountryDialCode { DialCode = "+64", PersianCountryName = "نیوزلند", EnglishCountryName = "New Zealand" },
            new CountryDialCode { DialCode = "+65", PersianCountryName = "سنگاپور", EnglishCountryName = "Singapore" },
            new CountryDialCode { DialCode = "+66", PersianCountryName = "تایلند", EnglishCountryName = "Thailand" },
            new CountryDialCode { DialCode = "+67", PersianCountryName = "فلیپین", EnglishCountryName = "Philippines" },
            new CountryDialCode { DialCode = "+68", PersianCountryName = "مالدیو", EnglishCountryName = "Maldives" },
            new CountryDialCode { DialCode = "+69", PersianCountryName = "سریلانکا", EnglishCountryName = "Sri Lanka" },
            new CountryDialCode { DialCode = "+7", PersianCountryName = "روسیه", EnglishCountryName = "Russia" },
            new CountryDialCode { DialCode = "+81", PersianCountryName = "ژاپن", EnglishCountryName = "Japan" },
            new CountryDialCode { DialCode = "+82", PersianCountryName = "کره جنوبی", EnglishCountryName = "South Korea" },
            new CountryDialCode { DialCode = "+84", PersianCountryName = "ویتنام", EnglishCountryName = "Vietnam" },
            new CountryDialCode { DialCode = "+86", PersianCountryName = "چین", EnglishCountryName = "China" },
            new CountryDialCode { DialCode = "+90", PersianCountryName = "ترکیه", EnglishCountryName = "Turkey" },
            new CountryDialCode { DialCode = "+91", PersianCountryName = "هند", EnglishCountryName = "India" },
            new CountryDialCode { DialCode = "+92", PersianCountryName = "پاکستان", EnglishCountryName = "Pakistan" },
            new CountryDialCode { DialCode = "+93", PersianCountryName = "افغانستان", EnglishCountryName = "Afghanistan" },
            new CountryDialCode { DialCode = "+94", PersianCountryName = "سریلانکا", EnglishCountryName = "Sri Lanka" },
            new CountryDialCode { DialCode = "+95", PersianCountryName = "میانمار", EnglishCountryName = "Myanmar" },
            new CountryDialCode { DialCode = "+212", PersianCountryName = "مراکش", EnglishCountryName = "Morocco" },
            new CountryDialCode { DialCode = "+213", PersianCountryName = "الجزایر", EnglishCountryName = "Algeria" },
            new CountryDialCode { DialCode = "+216", PersianCountryName = "تونس", EnglishCountryName = "Tunisia" },
            new CountryDialCode { DialCode = "+218", PersianCountryName = "لیبی", EnglishCountryName = "Libya" },
            new CountryDialCode { DialCode = "+220", PersianCountryName = "گامبیا", EnglishCountryName = "Gambia" },
            new CountryDialCode { DialCode = "+221", PersianCountryName = "سنگال", EnglishCountryName = "Senegal" },
            new CountryDialCode { DialCode = "+222", PersianCountryName = "موریتانی", EnglishCountryName = "Mauritania" },
            new CountryDialCode { DialCode = "+223", PersianCountryName = "مالی", EnglishCountryName = "Mali" },
            new CountryDialCode { DialCode = "+224", PersianCountryName = "گینه", EnglishCountryName = "Guinea" },
            new CountryDialCode { DialCode = "+225", PersianCountryName = "ساحل عاج", EnglishCountryName = "Ivory Coast" },
            new CountryDialCode { DialCode = "+226", PersianCountryName = "بورکینافاسو", EnglishCountryName = "Burkina Faso" },
            new CountryDialCode { DialCode = "+227", PersianCountryName = "نیجر", EnglishCountryName = "Niger" },
            new CountryDialCode { DialCode = "+228", PersianCountryName = "توغو", EnglishCountryName = "Togo" },
            new CountryDialCode { DialCode = "+229", PersianCountryName = "بنین", EnglishCountryName = "Benin" },
            new CountryDialCode { DialCode = "+230", PersianCountryName = "موریس", EnglishCountryName = "Mauritius" },
            new CountryDialCode { DialCode = "+231", PersianCountryName = "لیبریا", EnglishCountryName = "Liberia" },
            new CountryDialCode { DialCode = "+232", PersianCountryName = "سیرالئون", EnglishCountryName = "Sierra Leone" },
            new CountryDialCode { DialCode = "+233", PersianCountryName = "غنا", EnglishCountryName = "Ghana" },
            new CountryDialCode { DialCode = "+234", PersianCountryName = "نیجریه", EnglishCountryName = "Nigeria" },
            new CountryDialCode { DialCode = "+235", PersianCountryName = "چاد", EnglishCountryName = "Chad" },
            new CountryDialCode { DialCode = "+236", PersianCountryName = "افریقای مرکزی", EnglishCountryName = "Central African Republic" },
            new CountryDialCode { DialCode = "+237", PersianCountryName = "کامرون", EnglishCountryName = "Cameroon" },
            new CountryDialCode { DialCode = "+238", PersianCountryName = "کیپ ورد", EnglishCountryName = "Cape Verde" },
            new CountryDialCode { DialCode = "+239", PersianCountryName = "سائوتومه و پرنسیپ", EnglishCountryName = "Sao Tome and Principe" },
            new CountryDialCode { DialCode = "+240", PersianCountryName = "گینه استوایی", EnglishCountryName = "Equatorial Guinea" },
            new CountryDialCode { DialCode = "+241", PersianCountryName = "گابون", EnglishCountryName = "Gabon" },
            new CountryDialCode { DialCode = "+242", PersianCountryName = "کنگو", EnglishCountryName = "Congo" },
            new CountryDialCode { DialCode = "+243", PersianCountryName = "زئیر", EnglishCountryName = "Zaire" },
            new CountryDialCode { DialCode = "+244", PersianCountryName = "آنگولا", EnglishCountryName = "Angola" },
            new CountryDialCode { DialCode = "+245", PersianCountryName = "گینه بیسائو", EnglishCountryName = "Guinea-Bissau" },
            new CountryDialCode { DialCode = "+246", PersianCountryName = "سرزمین های دور افتاده بریتانیا", EnglishCountryName = "British Indian Ocean Territory" },
            new CountryDialCode { DialCode = "+247", PersianCountryName = "آسام", EnglishCountryName = "Ascension Island" },
            new CountryDialCode { DialCode = "+248", PersianCountryName = "سیشل", EnglishCountryName = "Seychelles" },
            new CountryDialCode { DialCode = "+249", PersianCountryName = "سودان", EnglishCountryName = "Sudan" },
            new CountryDialCode { DialCode = "+250", PersianCountryName = "رواندا", EnglishCountryName = "Rwanda" },
            new CountryDialCode { DialCode = "+251", PersianCountryName = "اتیوپی", EnglishCountryName = "Ethiopia" },
            new CountryDialCode { DialCode = "+252", PersianCountryName = "سومالی", EnglishCountryName = "Somalia" },
            new CountryDialCode { DialCode = "+253", PersianCountryName = "جیبوتی", EnglishCountryName = "Djibouti" },
            new CountryDialCode { DialCode = "+254", PersianCountryName = "کنیا", EnglishCountryName = "Kenya" },
            new CountryDialCode { DialCode = "+255", PersianCountryName = "تانزانیا", EnglishCountryName = "Tanzania" },
            new CountryDialCode { DialCode = "+256", PersianCountryName = "اوگاندا", EnglishCountryName = "Uganda" },
            new CountryDialCode { DialCode = "+257", PersianCountryName = "بوروندی", EnglishCountryName = "Burundi" },
            new CountryDialCode { DialCode = "+258", PersianCountryName = "موزامبیک", EnglishCountryName = "Mozambique" },
            new CountryDialCode { DialCode = "+259", PersianCountryName = "زامبیا", EnglishCountryName = "Zambia" },
            new CountryDialCode { DialCode = "+260", PersianCountryName = "مالاوی", EnglishCountryName = "Malawi" },
            new CountryDialCode { DialCode = "+261", PersianCountryName = "ماداکاسکار", EnglishCountryName = "Madagascar" },
            new CountryDialCode { DialCode = "+262", PersianCountryName = "جزایر کومور", EnglishCountryName = "Comoros" },
            new CountryDialCode { DialCode = "+263", PersianCountryName = "زیمبابوه", EnglishCountryName = "Zimbabwe" },
            new CountryDialCode { DialCode = "+264", PersianCountryName = "نامیبیا", EnglishCountryName = "Namibia" },
            new CountryDialCode { DialCode = "+265", PersianCountryName = "لسوتو", EnglishCountryName = "Lesotho" },
            new CountryDialCode { DialCode = "+266", PersianCountryName = "اسواتینی", EnglishCountryName = "Eswatini" },
            new CountryDialCode { DialCode = "+267", PersianCountryName = "بتسوانا", EnglishCountryName = "Botswana" },
            new CountryDialCode { DialCode = "+268", PersianCountryName = "موریس", EnglishCountryName = "Mauritius" },
            new CountryDialCode { DialCode = "+269", PersianCountryName = "جزایر کومور", EnglishCountryName = "Comoros" },
            new CountryDialCode { DialCode = "+370", PersianCountryName = "لیتوانی", EnglishCountryName = "Lithuania" },
            new CountryDialCode { DialCode = "+371", PersianCountryName = "لتونی", EnglishCountryName = "Latvia" },
            new CountryDialCode { DialCode = "+372", PersianCountryName = "استونی", EnglishCountryName = "Estonia" },
            new CountryDialCode { DialCode = "+373", PersianCountryName = "مولداوی", EnglishCountryName = "Moldova" },
            new CountryDialCode { DialCode = "+374", PersianCountryName = "ارمنستان", EnglishCountryName = "Armenia" },
            new CountryDialCode { DialCode = "+375", PersianCountryName = "بلاروس", EnglishCountryName = "Belarus" },
            new CountryDialCode { DialCode = "+376", PersianCountryName = "آندورا", EnglishCountryName = "Andorra" },
            new CountryDialCode { DialCode = "+377", PersianCountryName = "موناکو", EnglishCountryName = "Monaco" },
            new CountryDialCode { DialCode = "+378", PersianCountryName = "سن مارینو", EnglishCountryName = "San Marino" },
            new CountryDialCode { DialCode = "+379", PersianCountryName = "یونان", EnglishCountryName = "Greece" },
            new CountryDialCode { DialCode = "+420", PersianCountryName = "چک", EnglishCountryName = "Czech Republic" },
            new CountryDialCode { DialCode = "+421", PersianCountryName = "اسلواکی", EnglishCountryName = "Slovakia" },
            new CountryDialCode { DialCode = "+423", PersianCountryName = "لیختن اشتاین", EnglishCountryName = "Liechtenstein" },
            new CountryDialCode { DialCode = "+501", PersianCountryName = "بلیز", EnglishCountryName = "Belize" },
            new CountryDialCode { DialCode = "+502", PersianCountryName = "گواتمالا", EnglishCountryName = "Guatemala" },
            new CountryDialCode { DialCode = "+503", PersianCountryName = "السالوادور", EnglishCountryName = "El Salvador" },
            new CountryDialCode { DialCode = "+504", PersianCountryName = "هندوراس", EnglishCountryName = "Honduras" },
            new CountryDialCode { DialCode = "+505", PersianCountryName = "نیکاراگوئه", EnglishCountryName = "Nicaragua" },
            new CountryDialCode { DialCode = "+506", PersianCountryName = "کاستاریکا", EnglishCountryName = "Costa Rica" },
            new CountryDialCode { DialCode = "+507", PersianCountryName = "پاناما", EnglishCountryName = "Panama" },
            new CountryDialCode { DialCode = "+508", PersianCountryName = "گوادلوپ", EnglishCountryName = "Guadeloupe" },
            new CountryDialCode { DialCode = "+509", PersianCountryName = "هائی تی", EnglishCountryName = "Haiti" },
            new CountryDialCode { DialCode = "+590", PersianCountryName = "فرانس گاوان", EnglishCountryName = "French Guiana" },
            new CountryDialCode { DialCode = "+591", PersianCountryName = "بولیوی", EnglishCountryName = "Bolivia" },
            new CountryDialCode { DialCode = "+592", PersianCountryName = "گیانای فرانسه", EnglishCountryName = "French Guiana" },
            new CountryDialCode { DialCode = "+593", PersianCountryName = "اکوادور", EnglishCountryName = "Ecuador" },
            new CountryDialCode { DialCode = "+594", PersianCountryName = "گیانا", EnglishCountryName = "Guyana" },
            new CountryDialCode { DialCode = "+595", PersianCountryName = "پاراگوئه", EnglishCountryName = "Paraguay" },
            new CountryDialCode { DialCode = "+596", PersianCountryName = "مارتینیک", EnglishCountryName = "Martinique" },
            new CountryDialCode { DialCode = "+597", PersianCountryName = "سورینام", EnglishCountryName = "Suriname" },
            new CountryDialCode { DialCode = "+598", PersianCountryName = "اروگوئه", EnglishCountryName = "Uruguay" },
            new CountryDialCode { DialCode = "+599", PersianCountryName = "جزایر ویرجین بریتانیا", EnglishCountryName = "British Virgin Islands" },
            new CountryDialCode { DialCode = "+670", PersianCountryName = "تیمور شرقی", EnglishCountryName = "East Timor" },
            new CountryDialCode { DialCode = "+672", PersianCountryName = "سرزمین های دور افتاده استرالیای غربی", EnglishCountryName = "Cocos (Keeling) Islands" },
            new CountryDialCode { DialCode = "+673", PersianCountryName = "برونئی", EnglishCountryName = "Brunei" },
            new CountryDialCode { DialCode = "+674", PersianCountryName = "نائورا", EnglishCountryName = "Nauru" },
            new CountryDialCode { DialCode = "+675", PersianCountryName = "پاپوآ گینه نو", EnglishCountryName = "Papua New Guinea" },
            new CountryDialCode { DialCode = "+676", PersianCountryName = "تونگا", EnglishCountryName = "Tonga" },
            new CountryDialCode { DialCode = "+677", PersianCountryName = "جزایر سلیمان", EnglishCountryName = "Solomon Islands" },
            new CountryDialCode { DialCode = "+678", PersianCountryName = "وانواتو", EnglishCountryName = "Vanuatu" },
            new CountryDialCode { DialCode = "+679", PersianCountryName = "فیجی", EnglishCountryName = "Fiji" },
            new CountryDialCode { DialCode = "+680", PersianCountryName = "پالائو", EnglishCountryName = "Palau" },
            new CountryDialCode { DialCode = "+681", PersianCountryName = "سماوای شرقی", EnglishCountryName = "American Samoa" },
            new CountryDialCode { DialCode = "+682", PersianCountryName = "جزایر کوک", EnglishCountryName = "Cook Islands" },
            new CountryDialCode { DialCode = "+683", PersianCountryName = "جزایر ویرجین ایالات متحده", EnglishCountryName = "U.S. Virgin Islands" },
            new CountryDialCode { DialCode = "+685", PersianCountryName = "ساموا", EnglishCountryName = "Samoa" },
            new CountryDialCode { DialCode = "+686", PersianCountryName = "کیش", EnglishCountryName = "Kyrgyzstan" },
            new CountryDialCode { DialCode = "+687", PersianCountryName = "نیو کاله", EnglishCountryName = "New Caledonia" },
            new CountryDialCode { DialCode = "+688", PersianCountryName = "تایوان", EnglishCountryName = "Taiwan" },
            new CountryDialCode { DialCode = "+689", PersianCountryName = "پلینزیای فرانسه", EnglishCountryName = "French Polynesia" },
            new CountryDialCode { DialCode = "+690", PersianCountryName = "جزایر مارشال", EnglishCountryName = "Marshall Islands" },
            new CountryDialCode { DialCode = "+691", PersianCountryName = "جزایر میکرونزی", EnglishCountryName = "Micronesia" },
            new CountryDialCode { DialCode = "+692", PersianCountryName = "تیلمود", EnglishCountryName = "Tajikistan" },
            new CountryDialCode { DialCode = "+693", PersianCountryName = "ازبکستان", EnglishCountryName = "Uzbekistan" },
            new CountryDialCode { DialCode = "+694", PersianCountryName = "قرقیزستان", EnglishCountryName = "Kyrgyzstan" },
            new CountryDialCode { DialCode = "+695", PersianCountryName = "تاجیکستان", EnglishCountryName = "Tajikistan" },
            new CountryDialCode { DialCode = "+796", PersianCountryName = "روسیه", EnglishCountryName = "Russia" },
            new CountryDialCode { DialCode = "+797", PersianCountryName = "قرقیزستان", EnglishCountryName = "Kyrgyzstan" },
            new CountryDialCode { DialCode = "+798", PersianCountryName = "ترکمنستان", EnglishCountryName = "Turkmenistan" },
            new CountryDialCode { DialCode = "+799", PersianCountryName = "قزاقستان", EnglishCountryName = "Kazakhstan" },
            new CountryDialCode { DialCode = "+800", PersianCountryName = "خط تماس رایگان جهانی", EnglishCountryName = "Universal Freephone Service" },
            new CountryDialCode { DialCode = "+808", PersianCountryName = "خط تماس رایگان ایالات متحده", EnglishCountryName = "U.S. Toll-Free Service" },
            new CountryDialCode { DialCode = "+850", PersianCountryName = "کره شمالی", EnglishCountryName = "North Korea" },
            new CountryDialCode { DialCode = "+852", PersianCountryName = "هنگ کنگ", EnglishCountryName = "Hong Kong" },
            new CountryDialCode { DialCode = "+853", PersianCountryName = "ماکائو", EnglishCountryName = "Macau" },
            new CountryDialCode { DialCode = "+855", PersianCountryName = "کامبوج", EnglishCountryName = "Cambodia" },
            new CountryDialCode { DialCode = "+856", PersianCountryName = "لائوس", EnglishCountryName = "Laos" },
            new CountryDialCode { DialCode = "+960", PersianCountryName = "مالدیو", EnglishCountryName = "Maldives" },
            new CountryDialCode { DialCode = "+961", PersianCountryName = "لبنان", EnglishCountryName = "Lebanon" },
            new CountryDialCode { DialCode = "+962", PersianCountryName = "اردن", EnglishCountryName = "Jordan" },
            new CountryDialCode { DialCode = "+963", PersianCountryName = "سوریه", EnglishCountryName = "Syria" },
            new CountryDialCode { DialCode = "+964", PersianCountryName = "عراق", EnglishCountryName = "Iraq" },
            new CountryDialCode { DialCode = "+965", PersianCountryName = "کویت", EnglishCountryName = "Kuwait" },
            new CountryDialCode { DialCode = "+966", PersianCountryName = "عربستان", EnglishCountryName = "Saudi Arabia" },
            new CountryDialCode { DialCode = "+967", PersianCountryName = "یمن", EnglishCountryName = "Yemen" },
            new CountryDialCode { DialCode = "+968", PersianCountryName = "عمان", EnglishCountryName = "Oman" },
            new CountryDialCode { DialCode = "+970", PersianCountryName = "فلسطین", EnglishCountryName = "Palestine" },
            new CountryDialCode { DialCode = "+971", PersianCountryName = "امارات", EnglishCountryName = "United Arab Emirates" },
            new CountryDialCode { DialCode = "+972", PersianCountryName = "اسرائیل", EnglishCountryName = "Israel" },
            new CountryDialCode { DialCode = "+973", PersianCountryName = "بحرین", EnglishCountryName = "Bahrain" },
            new CountryDialCode { DialCode = "+974", PersianCountryName = "قطر", EnglishCountryName = "Qatar" },
            new CountryDialCode { DialCode = "+975", PersianCountryName = "برونئی", EnglishCountryName = "Brunei" },
            new CountryDialCode { DialCode = "+976", PersianCountryName = "مغولستان", EnglishCountryName = "Mongolia" },
            new CountryDialCode { DialCode = "+977", PersianCountryName = "نپال", EnglishCountryName = "Nepal" },
            new CountryDialCode { DialCode = "+979", PersianCountryName = "تبت", EnglishCountryName = "Tibet" },
            new CountryDialCode { DialCode = "+992", PersianCountryName = "تاجیکستان", EnglishCountryName = "Tajikistan" },
            new CountryDialCode { DialCode = "+993", PersianCountryName = "ترکمنستان", EnglishCountryName = "Turkmenistan" },
            new CountryDialCode { DialCode = "+994", PersianCountryName = "آذربایجان", EnglishCountryName = "Azerbaijan" },
            new CountryDialCode { DialCode = "+995", PersianCountryName = "گرجستان", EnglishCountryName = "Georgia" },
            new CountryDialCode { DialCode = "+996", PersianCountryName = "قرقیزستان", EnglishCountryName = "Kyrgyzstan" },
            new CountryDialCode { DialCode = "+998", PersianCountryName = "ازبکستان", EnglishCountryName = "Uzbekistan" },
            new CountryDialCode { DialCode = "+1242", PersianCountryName = "باهماس", EnglishCountryName = "Bahamas" },
            new CountryDialCode { DialCode = "+1246", PersianCountryName = "باربادوس", EnglishCountryName = "Barbados" },
            new CountryDialCode { DialCode = "+1264", PersianCountryName = "انگوشیند", EnglishCountryName = "Anguilla" },
            new CountryDialCode { DialCode = "+1268", PersianCountryName = "آنتیگوا و باربودا", EnglishCountryName = "Antigua and Barbuda" },
            new CountryDialCode { DialCode = "+1284", PersianCountryName = "جزایر ویرجین ایالات متحده", EnglishCountryName = "U.S. Virgin Islands" },
            new CountryDialCode { DialCode = "+1340", PersianCountryName = "جزایر ویرجین بریتانیا", EnglishCountryName = "British Virgin Islands" },
            new CountryDialCode { DialCode = "+1441", PersianCountryName = "جزایر برمودا", EnglishCountryName = "Bermuda" },
            new CountryDialCode { DialCode = "+1473", PersianCountryName = "گرنادا", EnglishCountryName = "Grenada" },
            new CountryDialCode { DialCode = "+1649", PersianCountryName = "ترنداد و توباگو", EnglishCountryName = "Trinidad and Tobago" },
            new CountryDialCode { DialCode = "+1664", PersianCountryName = "سنت هلیا", EnglishCountryName = "Saint Helena" },
            new CountryDialCode { DialCode = "+1670", PersianCountryName = "ساوانا", EnglishCountryName = "Saba" },
            new CountryDialCode { DialCode = "+1671", PersianCountryName = "جزایر ماریانا", EnglishCountryName = "Northern Mariana Islands" },
            new CountryDialCode { DialCode = "+1678", PersianCountryName = "سنت کitts و نیویس", EnglishCountryName = "Saint Kitts and Nevis" },
            new CountryDialCode { DialCode = "+1684", PersianCountryName = "ساموآ آمریکا", EnglishCountryName = "American Samoa" },
            new CountryDialCode { DialCode = "+1758", PersianCountryName = "سنت لوسیا", EnglishCountryName = "Saint Lucia" },
            new CountryDialCode { DialCode = "+1784", PersianCountryName = "سنت وینسنت و گرانادین ها", EnglishCountryName = "Saint Vincent and the Grenadines" },
            new CountryDialCode { DialCode = "+1868", PersianCountryName = "ترینیداد و توباگو", EnglishCountryName = "Trinidad and Tobago" },
            new CountryDialCode { DialCode = "+2121", PersianCountryName = "اتریش", EnglishCountryName = "Austria" },
            new CountryDialCode { DialCode = "+2181", PersianCountryName = "لیبی", EnglishCountryName = "Libya" },
            new CountryDialCode { DialCode = "+2081", PersianCountryName = "اسرائیل", EnglishCountryName = "Israel" },
            new CountryDialCode { DialCode = "+2201", PersianCountryName = "سنگال", EnglishCountryName = "Senegal" },
            new CountryDialCode { DialCode = "+2211", PersianCountryName = "سودان", EnglishCountryName = "Sudan" },
            new CountryDialCode { DialCode = "+2261", PersianCountryName = "بنگلادش", EnglishCountryName = "Bangladesh" },
            new CountryDialCode { DialCode = "+2351", PersianCountryName = "شارجه", EnglishCountryName = "Sharjah" },
            new CountryDialCode { DialCode = "+2401", PersianCountryName = "یمن", EnglishCountryName = "Yemen" },
            new CountryDialCode { DialCode = "+2541", PersianCountryName = "کنیا", EnglishCountryName = "Kenya" },
            new CountryDialCode { DialCode = "+2631", PersianCountryName = "زیمبابوه", EnglishCountryName = "Zimbabwe" },
            new CountryDialCode { DialCode = "+5011", PersianCountryName = "بلیز", EnglishCountryName = "Belize" },
            new CountryDialCode { DialCode = "+5031", PersianCountryName = "السالوادور", EnglishCountryName = "El Salvador" },
            new CountryDialCode { DialCode = "+5051", PersianCountryName = "نیکاراگوئه", EnglishCountryName = "Nicaragua" },
            new CountryDialCode { DialCode = "+6061", PersianCountryName = "فیلیپین", EnglishCountryName = "Philippines" },
            new CountryDialCode { DialCode = "+6291", PersianCountryName = "کوبا", EnglishCountryName = "Cuba" },
            new CountryDialCode { DialCode = "+6511", PersianCountryName = "بحرین", EnglishCountryName = "Bahrain" },
            new CountryDialCode { DialCode = "+6621", PersianCountryName = "ویتنام", EnglishCountryName = "Vietnam" },
            new CountryDialCode { DialCode = "+6731", PersianCountryName = "برونئی", EnglishCountryName = "Brunei" },
            new CountryDialCode { DialCode = "+6771", PersianCountryName = "جزایر سلیمان", EnglishCountryName = "Solomon Islands" },
            new CountryDialCode { DialCode = "+6781", PersianCountryName = "نیو کاله", EnglishCountryName = "New Caledonia" },
            new CountryDialCode { DialCode = "+6791", PersianCountryName = "فیجی", EnglishCountryName = "Fiji" },
            new CountryDialCode { DialCode = "+6861", PersianCountryName = "کره شمالی", EnglishCountryName = "North Korea" },
            new CountryDialCode { DialCode = "+6881", PersianCountryName = "تایوان", EnglishCountryName = "Taiwan" },
            new CountryDialCode { DialCode = "+6891", PersianCountryName = "جزایر کوک", EnglishCountryName = "Cook Islands" },
            new CountryDialCode { DialCode = "+6901", PersianCountryName = "جزایر مارشال", EnglishCountryName = "Marshall Islands" },
            new CountryDialCode { DialCode = "+6911", PersianCountryName = "جزایر میکرونزی", EnglishCountryName = "Micronesia" },
            new CountryDialCode { DialCode = "+7361", PersianCountryName = "ترکمنستان", EnglishCountryName = "Turkmenistan" },
            new CountryDialCode { DialCode = "+7721", PersianCountryName = "تاجیکستان", EnglishCountryName = "Tajikistan" },
            new CountryDialCode { DialCode = "+7971", PersianCountryName = "قزاقستان", EnglishCountryName = "Kazakhstan" },
            new CountryDialCode { DialCode = "+8701", PersianCountryName = "روسیه", EnglishCountryName = "Russia" },
            new CountryDialCode { DialCode = "+8801", PersianCountryName = "هند", EnglishCountryName = "India" },
            new CountryDialCode { DialCode = "+8861", PersianCountryName = "هنگ کنگ", EnglishCountryName = "Hong Kong" },
            new CountryDialCode { DialCode = "+9611", PersianCountryName = "لبنان", EnglishCountryName = "Lebanon" },
            new CountryDialCode { DialCode = "+9621", PersianCountryName = "اردن", EnglishCountryName = "Jordan" },
            new CountryDialCode { DialCode = "+9631", PersianCountryName = "سوریه", EnglishCountryName = "Syria" },
            new CountryDialCode { DialCode = "+9641", PersianCountryName = "عراق", EnglishCountryName = "Iraq" },
            new CountryDialCode { DialCode = "+9651", PersianCountryName = "کویت", EnglishCountryName = "Kuwait" },
            new CountryDialCode { DialCode = "+9661", PersianCountryName = "عربستان", EnglishCountryName = "Saudi Arabia" },
            new CountryDialCode { DialCode = "+9671", PersianCountryName = "یمن", EnglishCountryName = "Yemen" },
            new CountryDialCode { DialCode = "+9681", PersianCountryName = "عمان", EnglishCountryName = "Oman" },
            new CountryDialCode { DialCode = "+9701", PersianCountryName = "فلسطین", EnglishCountryName = "Palestine" },
            new CountryDialCode { DialCode = "+9711", PersianCountryName = "امارات", EnglishCountryName = "United Arab Emirates" },
            new CountryDialCode { DialCode = "+9721", PersianCountryName = "اسرائیل", EnglishCountryName = "Israel" },
            new CountryDialCode { DialCode = "+9731", PersianCountryName = "بحرین", EnglishCountryName = "Bahrain" },
            new CountryDialCode { DialCode = "+9741", PersianCountryName = "قطر", EnglishCountryName = "Qatar" },
            new CountryDialCode { DialCode = "+9751", PersianCountryName = "برونئی", EnglishCountryName = "Brunei" },
            new CountryDialCode { DialCode = "+9761", PersianCountryName = "مغولستان", EnglishCountryName = "Mongolia" },
            new CountryDialCode { DialCode = "+9771", PersianCountryName = "نپال", EnglishCountryName = "Nepal" },
            new CountryDialCode { DialCode = "+9791", PersianCountryName = "تبت", EnglishCountryName = "Tibet" },
            new CountryDialCode { DialCode = "+9921", PersianCountryName = "تاجیکستان", EnglishCountryName = "Tajikistan" },
            new CountryDialCode { DialCode = "+9931", PersianCountryName = "ترکمنستان", EnglishCountryName = "Turkmenistan" },
            new CountryDialCode { DialCode = "+9941", PersianCountryName = "آذربایجان", EnglishCountryName = "Azerbaijan" },
            new CountryDialCode { DialCode = "+9951", PersianCountryName = "گرجستان", EnglishCountryName = "Georgia" },
            new CountryDialCode { DialCode = "+9961", PersianCountryName = "قرقیزستان", EnglishCountryName = "Kyrgyzstan" },
            new CountryDialCode { DialCode = "+9981", PersianCountryName = "ازبکستان", EnglishCountryName = "Uzbekistan" }
        };

        public static string GetPersianCountryByDialCode(string dialCode)
        {
            var entry = CountryDialCodes.FirstOrDefault(x => x.DialCode == dialCode);
            return entry?.PersianCountryName;
        }

        public static string GetEnglishCountryByDialCode(string dialCode)
        {
            var entry = CountryDialCodes.FirstOrDefault(x => x.DialCode == dialCode);
            return entry?.EnglishCountryName;
        }

        public static string GetDialCodeByPersianCountry(string persianCountryName)
        {
            var entry = CountryDialCodes.FirstOrDefault(x => x.PersianCountryName == persianCountryName);
            return entry?.DialCode;
        }

        public static string GetDialCodeByEnglishCountry(string englishCountryName)
        {
            var entry = CountryDialCodes.FirstOrDefault(x => x.EnglishCountryName == englishCountryName);
            return entry?.DialCode;
        }

        public static List<CountryDialCode> GetAllCountriesSortedByDialCode()
        {
            return CountryDialCodes.OrderBy(x => int.Parse(x.DialCode.Trim('+'))).ToList();
        }
    }
}
